version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: taskmaster_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskmaster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: taskmaster_redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: taskmaster_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  postgres_data:
